// <auto-generated />
using CoursePlayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursePlayer.Data.Migrations
{
    [DbContext(typeof(CoursePlayerDbContext))]
    [Migration("20260825132146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("CoursePlayer.Data.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("CourseId", "FilePath")
                        .IsUnique();

                    b.HasIndex("CourseId", "OrderIndex");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CoursePlayer.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastOpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastOpenedAt");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoursePlayer.Data.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastPage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WatchedSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("LastAccessedAt");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("CoursePlayer.Data.Asset", b =>
                {
                    b.HasOne("CoursePlayer.Data.Course", "Course")
                        .WithMany("Assets")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CoursePlayer.Data.Progress", b =>
                {
                    b.HasOne("CoursePlayer.Data.Asset", "Asset")
                        .WithOne("Progress")
                        .HasForeignKey("CoursePlayer.Data.Progress", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CoursePlayer.Data.Asset", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("CoursePlayer.Data.Course", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
